### ISSUE TITLE
who are the keynotes?

### ISSUE THREAD

**Issue by timm** [ssbse17/ssbse17.github.io#2]
page1 says "keynotes announced"

and they are???

**Comment by larsgrunske** [comment]
Can you please  ask for Title, Abstract, Picture and Bio similar to: http://ssbse.org/2016/speaker/carlos-artemio-coello-coello/#more-940 for our two academic keynote speaker.

**Comment by justynapt** [comment]
Myra Cohen (already agreed)
Yuanyuan Zhang (waiting for a reply)
Joachim Wagner (Lars - what's the status?)

**Comment by larsgrunske** [comment]
JW is confirmed and I try to get the material for the HP

**Comment by justynapt** [comment]
Yuanyuan declined

**Comment by justynapt** [comment]
Keynote information on the website. Closing.
