### ISSUE TITLE
please check this pc invite text

### ISSUE THREAD

**Issue by timm** [ssbse17/ssbse17.github.io#3]
Dear [_FIRST-NAME_],

We hope this e-mail finds you well!

Please, can you let me know if you can accept or not our invitation to join the Program Committee for SSBSE 2017? (see details below).

It would be great yo have you on board, but if you are too busy I do understand :-)

Looking forward to seeing you at Raleigh!

Best Regards,
Tim & Justyna
## 

We are pleased to invite you to join the Program Committee (PC) for the 9th Symposium on Search Based Software Engineering (SSBSE 2017,http://ssbse17.github.io/).

As a PC member, your main responsibilities will be to review research papers, short papers and challenge papers, and to participate in the online discussion of papers for inclusion in the final program. The exact number of submissions to be reviewed depends on how many submissions we get but, as a guide, we would guess 3 to 8 papers per reviewer.

For the main research track the timeline is as follows:
- Abstract submission March 31, 2017
- April 1 to 6, bidding for papers on title & abstract
- Paper Submission April 7,  
- Papers assigned to reviewers, April 8
- Paper reviews due May 5,
- On-line discussion May 6 to 12.
- Decisions finalized May 13. 
- Notification May 14, 2017 

For the short papers track and challenge track the timeline is as follows:
- Submission May 21, 2017
- May 22 to 26: bidding on papers title & abstract
- Papers signed to reviewers May 27.
- Paper reviews due June 2
- On-line discussion June 3 to 5
- Decisions finalized June 6
- Notification June 7

The review process will be carried online through EasyChair.

It is crucial that we keep to our schedule and that all deadlines to the authors are met. Therefore, please ensure that you will be able to meet the reviewing commitments and constraints before accepting this invitation.

You are also strongly encouraged to help with the following duties:
- solicit high-quality papers from colleagues and distribute conference announcements to your contacts. PC members are strongly encouraged to submit as well. The General Chair and the PC Co-Chairs will not submit papers.
- attend the conference and chair a session. The SSBE 2017 conference co-located with ESEC/FSE’17 Paderborn, Germany, September 9-11, 2017 

We expect each PC member to provide sound and constructive comments in his/her field of expertise. PC members should complete the reviews themselves but may ask a colleague or student for ideas and sanity checks on the review they are responsible for (and finally write). Even if you ask for help, you will be expected to have read the paper and to assume full ownership and responsibility for the full content of the review. You will also be expected to support your review during the online discussion phase.

Because your contribution as a PC member is crucial for the success of the conference, we plan to give an award for distinguished reviewers.

Please respond to this invitation by 24th September 2017. If you accept our invitation, please ensure that EasyChair has correct information about you (name, affiliation, home page URL) so that we can be accurate in our publicity.

We look forward to working with you to make SSBSE 2017 a resounding success and expecting to receive your contribution before May 5, 2017.

If you have any questions, please feel free to contact us.

Kind Regards,  
Tim Menzues (program co-chair) tim@menzies.us  
Justyna Petke (program co-chair) j.petke@ucl.ac.uk

**Comment by justynapt** [comment]
ok, either set a deadline for responding or set it in the next email

**Comment by larsgrunske** [comment]
OK!

**Comment by justynapt** [comment]
PC members invited. Closing.
